branches:
  only:
    - main
language: node_js
node_js:
  - 16

services:
  - docker

script:
## Build
  - docker-compose -f docker-compose-build.yaml build
## Tagging
  - docker tag udagram-api-feed imdt2502/udagram-api-feed:latest
  - docker tag udagram-api-user imdt2502/udagram-api-user:latest
  - docker tag udagram-frontend imdt2502/udagram-frontend:latest
  - docker tag reverseproxy imdt2502/reverseproxy:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
## Push
  - docker push imdt2502/udagram-api-feed
  - docker push imdt2502/udagram-api-user
  - docker push imdt2502/udagram-frontend
  - docker push imdt2502/reverseproxy